### ISSUE TITLE
certificate rejected [SelfSigned]

### ISSUE THREAD

**Issue by xavierf38700** [nanoporetech/ont_tutorial_cas9#2]
Hi, 

When I follow this tutorial, i have an error when fetching the ONT logo when connecting to this page : https://nanoporetech.com/themes/custom/nanopore/images/ont-logo.svg

So I delete the line 25 in the ont_tutorial_cas9.Rmd file, and it works perfectly.

Thank for the tutorial,

Xavier

**Comment by sagrudd** [comment]
Thanks for the feedback - I think that this certificate issue was fixed a while back? I am closing this issue - is this OK?
