### ISSUE TITLE
order of installation of git-lfs to conda environment

### ISSUE THREAD

**Issue by monkollek** [nanoporetech/ont_tutorial_cas9#8]
Currently git-lfs is installed in the conda environment in step 2
conda install -c conda-forge git-lfs

For most like me this will cause an error as we don't have privileged root/sudo access and it can't write to the correct directories.

I actually did this after step 5, that is after creating environment (step 4) and activating it
conda activate ont_tutorial_cas9

This will then install git-lfs in your conda environment which you do have write access.
Better yet, it should be in the environment.yaml file so it's automatically installed in step 4.

**Comment by sagrudd** [comment]
git_lfs needs to be installed prior to the environment.yaml step since the entire repository is downloaded (git pull) and this requires git_lfs for the fastq content. I am interested in your environment; are you working with a compute environment where conda has been installed centrally?

**Comment by monkollek** [comment]
yes conda is installed centrally and is usually the case with institutional clusters. I can't see why the following commands can't happen after the conda environment is created (that is after step 5)

git lfs install
git clone https://github.com/nanoporetech/ont_tutorial_cas9.git ont_tutorial_cas9

as it's just code and it worked fine for me, including grabbing the fastq files. Anyways, it's just a suggestion for those with conda installed centrally.

**Comment by sagrudd** [comment]
Agree completely; you have a solution here and this makes sense! The specification for the tutorials at outset was that we would like to help users get started with bioinformatics on their own laptops and devices. In some of our other tutorials the `git clone` requires `git-lfs` and, my apologies, I was unaware that cluster conda installations were a thing.

We have updates to the way that tutorials are handled and presented in development - we will be moving away from the dependency for conda and git-lfs - please watch this space.
